[build]
  publish = "."

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/paper.html"
  [headers.values]
    X-Robots-Tag = "noindex"
